name: Debug Curl
on: workflow_dispatch
jobs:
  debug:
    runs-on: ubuntu-latest
    container: debian:10
    steps:
      - run: |
          sed -i -e 's/deb.debian.org/archive.debian.org/g' -e 's|security.debian.org|archive.debian.org/|g' -e '/stretch-updates/d' /etc/apt/sources.list
          echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/10no--check-valid-until
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y libcurl4-openssl-dev findutils
          find /usr -name "easy.h"
          find /usr -name "libcurl*"
